stages:
  - build
  - test

build:
  stage: build
  image: registry.gitlab.com/tilak.io/tiplotci
  before_script:
    - ls
    - mv /docker_tiplot/* .
    - ls
    - pwd
    - CI= yarn install
  script:
    - CI= yarn build:api
    - CI= yarn build:electron
  artifacts:
    paths:
      - dist/*.AppImage
#  only:
#    - main
