name: Building Executable
run-name: ${{ github.actor }} is buildling TiPlot 🚀
on:
  push:
    branches:
      - main
jobs:
  Build-AppImage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: tree
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: api/requirements.txt
      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        # the package installation will only be executed when the
        # requirements-files have changed.
      - run: pip install -r api/requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - name: install node dependecies
        run: yarn install
      - name: build backend
        run: yarn build:api
      - name: build desktop app
        env:
          GH_TOKEN: ${{ github.token }}
          # CI: false # ignore warnings
        run: yarn build:electron

  Build-EXE:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: tree
      - name: install node dependecies
        run: yarn install
      - run: pip install -r api/requirements.txt
      - name: build backend
        run: yarn build:api
      - name: build desktop app
        env:
          GH_TOKEN: ${{ github.token }}
          # CI: false # ignore warnings
        run: yarn build:electron
